version: "3.7"
services:
  postgres:
    image: postgres:alpine
    volumes:
      - ./schema/create.sql:/docker-entrypoint-initdb.d/create.sql
    restart: always
    env_file:
      - ./config/.env
    ports:
      - "5433:5432"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - "8003:8003"
volumes:
  data: